# -*- coding: utf-8 -*-
"""metrics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZYvxalC60K4Pr3YPQJ0_80irkP146_7-
"""

from __future__ import annotations

from typing import Dict

import numpy as np


ArrayLike = np.ndarray


def _validate_same_shape(y_true: ArrayLike, y_pred: ArrayLike) -> None:
    if y_true.shape != y_pred.shape:
        raise ValueError("y_true and y_pred must have the same shape.")


def _binarize(arr: ArrayLike, threshold: float = 0.5) -> ArrayLike:
    arr = np.asarray(arr)
    return (arr >= threshold).astype(np.uint8)


def dice_score(
    y_true: ArrayLike,
    y_pred: ArrayLike,
    threshold: float = 0.5,
) -> float:
    """
    Compute Dice Similarity Coefficient for binary masks.
    """
    y_true = _binarize(y_true, threshold)
    y_pred = _binarize(y_pred, threshold)
    _validate_same_shape(y_true, y_pred)

    intersection = np.sum(y_true * y_pred)
    total = np.sum(y_true) + np.sum(y_pred)

    if total == 0:
        return 1.0

    return float((2.0 * intersection) / total)


def iou_score(
    y_true: ArrayLike,
    y_pred: ArrayLike,
    threshold: float = 0.5,
) -> float:
    """
    Compute Intersection over Union for binary masks.
    """
    y_true = _binarize(y_true, threshold)
    y_pred = _binarize(y_pred, threshold)
    _validate_same_shape(y_true, y_pred)

    intersection = np.sum(y_true * y_pred)
    union = np.sum((y_true + y_pred) > 0)

    if union == 0:
        return 1.0

    return float(intersection / union)


def precision_score(
    y_true: ArrayLike,
    y_pred: ArrayLike,
    threshold: float = 0.5,
) -> float:
    """
    Compute precision for binary masks.
    """
    y_true = _binarize(y_true, threshold)
    y_pred = _binarize(y_pred, threshold)
    _validate_same_shape(y_true, y_pred)

    tp = np.sum((y_true == 1) & (y_pred == 1))
    fp = np.sum((y_true == 0) & (y_pred == 1))

    if tp + fp == 0:
        return 1.0

    return float(tp / (tp + fp))


def recall_score(
    y_true: ArrayLike,
    y_pred: ArrayLike,
    threshold: float = 0.5,
) -> float:
    """
    Compute recall for binary masks.
    """
    y_true = _binarize(y_true, threshold)
    y_pred = _binarize(y_pred, threshold)
    _validate_same_shape(y_true, y_pred)

    tp = np.sum((y_true == 1) & (y_pred == 1))
    fn = np.sum((y_true == 1) & (y_pred == 0))

    if tp + fn == 0:
        return 1.0

    return float(tp / (tp + fn))


def accuracy_score(
    y_true: ArrayLike,
    y_pred: ArrayLike,
    threshold: float = 0.5,
) -> float:
    """
    Compute pixel-wise accuracy for binary masks.
    """
    y_true = _binarize(y_true, threshold)
    y_pred = _binarize(y_pred, threshold)
    _validate_same_shape(y_true, y_pred)

    return float(np.mean(y_true == y_pred))


def hausdorff_distance_placeholder() -> str:
    """
    Placeholder description for Hausdorff Distance.

    This repository focuses on lightweight, portfolio-style examples.
    A full Hausdorff implementation can be added later with SciPy or MedPy.
    """
    return "Hausdorff Distance placeholder: add a full implementation if needed."


def summarise_metrics(
    y_true: ArrayLike,
    y_pred: ArrayLike,
    threshold: float = 0.5,
) -> Dict[str, float | str]:
    """
    Return a compact summary of segmentation metrics.
    """
    return {
        "dice": dice_score(y_true, y_pred, threshold),
        "iou": iou_score(y_true, y_pred, threshold),
        "precision": precision_score(y_true, y_pred, threshold),
        "recall": recall_score(y_true, y_pred, threshold),
        "accuracy": accuracy_score(y_true, y_pred, threshold),
        "hausdorff_distance": hausdorff_distance_placeholder(),
    }


if __name__ == "__main__":
    y_true = np.zeros((10, 10), dtype=np.uint8)
    y_pred = np.zeros((10, 10), dtype=np.uint8)

    y_true[2:6, 3:7] = 1
    y_pred[3:7, 4:8] = 1

    print(summarise_metrics(y_true, y_pred))