# -*- coding: utf-8 -*-
"""visualisation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kB6b1Mq3IJptK2NkGN44dMflo0ou5pp_
"""

from __future__ import annotations

from typing import Iterable, Optional, Sequence

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ArrayLike = np.ndarray


def show_image(
    image: ArrayLike,
    title: str = "Image",
    cmap: str = "gray",
    figsize: tuple[int, int] = (5, 5),
) -> None:
    """
    Display a single 2D image.
    """
    image = np.asarray(image)

    plt.figure(figsize=figsize)
    plt.imshow(image, cmap=cmap)
    plt.title(title)
    plt.axis("off")
    plt.tight_layout()
    plt.show()


def show_side_by_side(
    images: Sequence[ArrayLike],
    titles: Sequence[str],
    cmap: str = "gray",
    figsize: tuple[int, int] = (12, 4),
) -> None:
    """
    Display multiple images in one row.
    """
    if len(images) != len(titles):
        raise ValueError("images and titles must have the same length.")

    fig, axes = plt.subplots(1, len(images), figsize=figsize)

    if len(images) == 1:
        axes = [axes]

    for ax, image, title in zip(axes, images, titles):
        ax.imshow(np.asarray(image), cmap=cmap)
        ax.set_title(title)
        ax.axis("off")

    plt.tight_layout()
    plt.show()


def overlay_mask(
    image: ArrayLike,
    mask: ArrayLike,
    alpha: float = 0.35,
    figsize: tuple[int, int] = (5, 5),
    title: str = "Image with Mask Overlay",
) -> None:
    """
    Overlay a binary mask on top of a grayscale image.
    """
    image = np.asarray(image)
    mask = np.asarray(mask)

    if image.shape != mask.shape:
        raise ValueError("image and mask must have the same shape.")

    plt.figure(figsize=figsize)
    plt.imshow(image, cmap="gray")
    plt.imshow(np.ma.masked_where(mask == 0, mask), alpha=alpha)
    plt.title(title)
    plt.axis("off")
    plt.tight_layout()
    plt.show()


def plot_metric_bars(
    df: pd.DataFrame,
    x_col: str,
    y_col: str,
    title: str,
    ylabel: str,
    rotation: int = 15,
    figsize: tuple[int, int] = (7, 4),
) -> None:
    """
    Plot a simple bar chart from a DataFrame.
    """
    if x_col not in df.columns or y_col not in df.columns:
        raise ValueError("Specified columns are not present in the DataFrame.")

    plt.figure(figsize=figsize)
    plt.bar(df[x_col], df[y_col])
    plt.title(title)
    plt.ylabel(ylabel)
    plt.xticks(rotation=rotation)
    plt.tight_layout()
    plt.show()


def plot_metric_lines(
    df: pd.DataFrame,
    x_col: str,
    y_cols: Iterable[str],
    title: str,
    ylabel: str,
    marker: str = "o",
    figsize: tuple[int, int] = (7, 4),
) -> None:
    """
    Plot one or more metric columns as line charts on a single figure.
    """
    if x_col not in df.columns:
        raise ValueError(f"{x_col} is not present in the DataFrame.")

    plt.figure(figsize=figsize)

    for col in y_cols:
        if col not in df.columns:
            raise ValueError(f"{col} is not present in the DataFrame.")
        plt.plot(df[x_col], df[col], marker=marker, label=col)

    plt.title(title)
    plt.ylabel(ylabel)
    plt.xticks(rotation=15)
    plt.legend()
    plt.tight_layout()
    plt.show()


def compare_segmentation_masks(
    y_true: ArrayLike,
    y_pred: ArrayLike,
    figsize: tuple[int, int] = (10, 4),
) -> None:
    """
    Display ground truth and predicted masks side by side.
    """
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)

    if y_true.shape != y_pred.shape:
        raise ValueError("y_true and y_pred must have the same shape.")

    fig, axes = plt.subplots(1, 2, figsize=figsize)

    axes[0].imshow(y_true, cmap="gray")
    axes[0].set_title("Ground Truth")
    axes[0].axis("off")

    axes[1].imshow(y_pred, cmap="gray")
    axes[1].set_title("Prediction")
    axes[1].axis("off")

    plt.tight_layout()
    plt.show()


def save_figure(
    path: str,
    dpi: int = 300,
    bbox_inches: str = "tight",
) -> None:
    """
    Save the current matplotlib figure.
    """
    plt.savefig(path, dpi=dpi, bbox_inches=bbox_inches)


if __name__ == "__main__":
    example = np.random.rand(128, 128)
    mask = np.zeros((128, 128))
    mask[40:80, 50:90] = 1

    show_image(example, title="Example Image")
    overlay_mask(example, mask, title="Overlay Example")

    df = pd.DataFrame(
        {
            "Model": ["Baseline 3D U-Net", "3D Improved U-Net", "2D Improved U-Net"],
            "DSC": [0.6047, 0.6667, 0.6804],
        }
    )
    plot_metric_bars(df, x_col="Model", y_col="DSC", title="Dice Score Comparison", ylabel="DSC")